<a href="https://colab.research.google.com/github/NataliyaSmirnovaKava/dz3/blob/main/%D0%A1%D0%BC%D0%B8%D1%80%D0%BD%D0%BE%D0%B2%D0%B0_%D0%9D_%D0%98_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Импортируйте библиотеку NumPy

In [ ]:
import numpy as np


In [ ]:
# Создайте массив из 10 нулей
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать массив из 10 единиц

In [ ]:
b=np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать массив из 10 пятерок

In [ ]:
import numpy as np
c=b*5
print(c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Создать массив из целых чисел от 10 до 50

In [ ]:
d=np.arange(10,51)
print (d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Создать массив из четных чисел от 10 до 50

In [ ]:
f=np.arange(10,51,2)
print (f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
z= np.arange(0,9). reshape (3,3)
print (z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Создать единичную матрицу 3x3

In [ ]:
h=np.eye (3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
i=np.random.rand (1)
print(i)

[0.1344064]


Используйте NumPy для генерации массива из 25 случайных чисел,
взятых из стандартного нормального распределения

In [ ]:
j=np.random.rand (25)
print(j)

[0.50371849 0.89576231 0.25611246 0.41195224 0.32623622 0.68378374
 0.81523307 0.13180935 0.55765555 0.22905372 0.17484342 0.12187578
 0.12017219 0.22037055 0.80418474 0.71047499 0.86704528 0.6010497
 0.95802625 0.69525534 0.30482984 0.31210809 0.36493658 0.05121129
 0.51773077]


Создайте следующую матрицу используя функции библиотеки NumPy:

In [ ]:
k=np.arange(0.01,1.01,0.01).reshape(10,10)
print (k)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


это наша стартовая матрица

Необходимо написать код который вернет следующую матрицу
из стартовой

In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицу
из стартовой

In [ ]:
print (mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Написать код обращения к элементу который вернет значение 20 из
стартовой матрицы задачи l

In [ ]:
ar=mat[mat==20]
print(ar)

[20]


Написать код к стартовой матрице задачи l , который воспроизводит
вывод, показанный ниже

In [ ]:
print(mat[0:3,1].reshape(3,1))

[[ 2]
 [ 7]
 [12]]


Написать код к стартовой матрице задачи l , который воспроизводит
вывод, показанный ниже

In [ ]:
print(mat[4])

[21 22 23 24 25]


Написать код к стартовой матрице задачи l , который воспроизводит
вывод, показанный ниже

In [ ]:
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


Получить сумму всех значений в стартовой матрице mat

In [ ]:
print(mat.sum())

325


Получить стандартное отклонение в стартовой матрице mat

In [ ]:
print(mat.std())

7.211102550927978


Получить сумму значений в колонках в стартовой матрице mat

In [ ]:
print(mat.sum(axis=0))

[55 60 65 70 75]
